inverted_pendulum:

  # Publish joint states
  joint_state_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  
  joint_cart_controller:
    type: effort_controllers/JointPositionController
    joint: cart_joint
    publish_rate: 200
    pid: {p: 30.0, i: 24, d: 15}



  